services:
  main-scraper:
    image: jthil23/main-scraper:latest
    pull_policy: always
    container_name: main-scraper
    env_file: .env
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
